chore: add metric for filtration time
zubr-exchange/cacherpc pull request #108
Opened 2021-09-03 17:04 UTC by polachok

2021-09-03 17:11 UTC, 00nktk requested changes

2021-09-03 17:11 UTC, 00nktk commented on src/accounts.rs
> +                            let filtration_starts = Instant::now();
Может подвинуть это на 760 строчку? Чтобы замерять только если есть фильтры

2021-09-05 11:32 UTC, polachok commented on src/accounts.rs
> +                            let filtration_starts = Instant::now();
👌🏼

2021-09-06 08:51 UTC, 00nktk approved these changes

2021-09-06 08:53 UTC, merged