Removed unwrap when starting control interface
zubr-exchange/cacherpc pull request #211
Opened 2021-11-17 12:00 UTC by bobs4462

2021-11-17 12:46 UTC, polachok requested changes

2021-11-17 12:46 UTC, polachok commented on src/control.rs
> +                warn!(%error, "Failed to run control interface server");
please add socket_path here too

2021-11-17 12:46 UTC, polachok commented on src/main.rs
> +                "Command processing error: {}\nMake sure control interface is running",
and here

2021-11-17 18:28 UTC, bobs4462 commented on src/main.rs
> +                "Command processing error: {}\nMake sure control interface is running",
Done

2021-11-18 10:43 UTC, polachok approved these changes

2021-11-19 05:00 UTC, merged